/* =========================================================
   大乱闘スマッシュブラザーズ SPECIAL 参戦ファイター定義
   ---------------------------------------------------------
   ICON_BASE:
     キャラアイコン画像の URL テンプレート。'{slug}' が各ファイターの
     slug に置換されます。既定ではリポジトリ内の assets/icons/ を参照し、
     画像が存在しない場合は自動でシリーズカラーのアバターにフォールバック
     します。外部 CDN を使う場合はここを書き換えてください。
       例) 'https://example.com/ssbu/{slug}.png'
     '' を指定すると常にフォールバックアバターを使用します。
   ========================================================= */
var ICON_BASE = 'assets/icons/{slug}.png';

/* シリーズ定義（アイコンのフォールバック配色に使用） */
var SERIES = {
  mario:        { label: 'マリオ',            colors: ['#e8453c', '#f79a2b'] },
  dk:           { label: 'ドンキーコング',    colors: ['#8a5a2b', '#c98f4a'] },
  zelda:        { label: 'ゼルダ',            colors: ['#2f9e5e', '#8fd66a'] },
  metroid:      { label: 'メトロイド',        colors: ['#e2622a', '#ffb347'] },
  yoshi:        { label: 'ヨッシー',          colors: ['#4caf50', '#a5e05a'] },
  kirby:        { label: 'カービィ',          colors: ['#f06fa8', '#ffb3d1'] },
  starfox:      { label: 'スターフォックス',  colors: ['#2f6fd0', '#61b3f5'] },
  pokemon:      { label: 'ポケモン',          colors: ['#f2c12e', '#ffe27a'] },
  earthbound:   { label: 'MOTHER',            colors: ['#d94f6e', '#ff97ad'] },
  fzero:        { label: 'F-ZERO',            colors: ['#2b3fa0', '#6f7ff0'] },
  ice:          { label: 'アイスクライマー',  colors: ['#3aa6c9', '#9fe0f0'] },
  fireemblem:   { label: 'ファイアーエムブレム', colors: ['#3f6fb5', '#8fb6ef'] },
  gameandwatch: { label: 'ゲーム&ウォッチ',   colors: ['#3a3f46', '#8b939e'] },
  kidicarus:    { label: '光神話 パルテナの鏡', colors: ['#3f9fd6', '#a7ddf5'] },
  wario:        { label: 'ワリオ',            colors: ['#e6c62e', '#b04fa0'] },
  metalgear:    { label: 'メタルギア',        colors: ['#5c6b4a', '#9fae86'] },
  pikmin:       { label: 'ピクミン',          colors: ['#e05c5c', '#f0a24a'] },
  animalcrossing: { label: 'どうぶつの森',    colors: ['#4bb26a', '#b5e57a'] },
  megaman:      { label: 'ロックマン',        colors: ['#2f8fe0', '#7fd0ff'] },
  wiifit:       { label: 'Wii Fit',           colors: ['#4ec2c2', '#a7ebe4'] },
  punchout:     { label: 'パンチアウト!!',    colors: ['#3f8f4f', '#87d18b'] },
  mii:          { label: 'Mii',               colors: ['#5b8def', '#9db9f5'] },
  pacman:       { label: 'パックマン',        colors: ['#f5d21e', '#ffea7a'] },
  xenoblade:    { label: 'ゼノブレイド',      colors: ['#c8442f', '#f08a5a'] },
  duckhunt:     { label: 'ダックハント',      colors: ['#a8792e', '#e0b96a'] },
  streetfighter:{ label: 'ストリートファイター', colors: ['#d84a2a', '#f5a25a'] },
  finalfantasy: { label: 'FINAL FANTASY',     colors: ['#5a6b8c', '#a9b8d6'] },
  bayonetta:    { label: 'ベヨネッタ',        colors: ['#6b3fa0', '#b78fe0'] },
  splatoon:     { label: 'スプラトゥーン',    colors: ['#e05fa8', '#6fe04a'] },
  sonic:        { label: 'ソニック',          colors: ['#2f5fd0', '#6f9ff5'] },
  rob:          { label: 'ロボット',          colors: ['#8a8f9a', '#c4c9d4'] },
  castlevania:  { label: '悪魔城ドラキュラ',  colors: ['#8a3a3a', '#c98a6a'] },
  persona:      { label: 'ペルソナ',          colors: ['#c8102e', '#ff6b6b'] },
  dragonquest:  { label: 'ドラゴンクエスト',  colors: ['#3f7fd0', '#8fc4f5'] },
  banjo:        { label: 'バンジョーとカズーイ', colors: ['#c98a2e', '#f0c46a'] },
  fatalfury:    { label: '餓狼伝説',          colors: ['#c94a2e', '#f09a6a'] },
  arms:         { label: 'ARMS',              colors: ['#e0714a', '#5bd0d0'] },
  minecraft:    { label: 'Minecraft',         colors: ['#5a9e4a', '#8ac46a'] },
  tekken:       { label: '鉄拳',              colors: ['#8a2f3f', '#d06a7a'] },
  kingdomhearts:{ label: 'キングダムハーツ',  colors: ['#3f4f8c', '#7f8fd6'] }
};

/* ファイター一覧（ファイター番号順・全 86 種） */
var FIGHTERS = [
  { name: 'マリオ',            slug: 'mario',             series: 'mario' },
  { name: 'ドンキーコング',    slug: 'donkey_kong',       series: 'dk' },
  { name: 'リンク',            slug: 'link',              series: 'zelda' },
  { name: 'サムス',            slug: 'samus',             series: 'metroid' },
  { name: 'ダークサムス',      slug: 'dark_samus',        series: 'metroid' },
  { name: 'ヨッシー',          slug: 'yoshi',             series: 'yoshi' },
  { name: 'カービィ',          slug: 'kirby',             series: 'kirby' },
  { name: 'フォックス',        slug: 'fox',               series: 'starfox' },
  { name: 'ピカチュウ',        slug: 'pikachu',           series: 'pokemon' },
  { name: 'ルイージ',          slug: 'luigi',             series: 'mario' },
  { name: 'ネス',              slug: 'ness',              series: 'earthbound' },
  { name: 'キャプテン・ファルコン', slug: 'captain_falcon', series: 'fzero' },
  { name: 'プリン',            slug: 'jigglypuff',        series: 'pokemon' },
  { name: 'ピーチ',            slug: 'peach',             series: 'mario' },
  { name: 'デイジー',          slug: 'daisy',             series: 'mario' },
  { name: 'クッパ',            slug: 'bowser',            series: 'mario' },
  { name: 'アイスクライマー',  slug: 'ice_climbers',      series: 'ice' },
  { name: 'シーク',            slug: 'sheik',             series: 'zelda' },
  { name: 'ゼルダ',            slug: 'zelda',             series: 'zelda' },
  { name: 'ドクターマリオ',    slug: 'dr_mario',          series: 'mario' },
  { name: 'ピチュー',          slug: 'pichu',             series: 'pokemon' },
  { name: 'ファルコ',          slug: 'falco',             series: 'starfox' },
  { name: 'マルス',            slug: 'marth',             series: 'fireemblem' },
  { name: 'ルキナ',            slug: 'lucina',            series: 'fireemblem' },
  { name: 'こどもリンク',      slug: 'young_link',        series: 'zelda' },
  { name: 'ガノンドロフ',      slug: 'ganondorf',         series: 'zelda' },
  { name: 'ミュウツー',        slug: 'mewtwo',            series: 'pokemon' },
  { name: 'ロイ',              slug: 'roy',               series: 'fireemblem' },
  { name: 'クロム',            slug: 'chrom',             series: 'fireemblem' },
  { name: 'Mr.ゲーム&ウォッチ', slug: 'mr_game_and_watch', series: 'gameandwatch' },
  { name: 'メタナイト',        slug: 'meta_knight',       series: 'kirby' },
  { name: 'ピット',            slug: 'pit',               series: 'kidicarus' },
  { name: 'ブラックピット',    slug: 'dark_pit',          series: 'kidicarus' },
  { name: 'ゼロスーツサムス',  slug: 'zero_suit_samus',   series: 'metroid' },
  { name: 'ワリオ',            slug: 'wario',             series: 'wario' },
  { name: 'スネーク',          slug: 'snake',             series: 'metalgear' },
  { name: 'アイク',            slug: 'ike',               series: 'fireemblem' },
  { name: 'ポケモントレーナー', slug: 'pokemon_trainer',  series: 'pokemon' },
  { name: 'ディディーコング',  slug: 'diddy_kong',        series: 'dk' },
  { name: 'リュカ',            slug: 'lucas',             series: 'earthbound' },
  { name: 'ソニック',          slug: 'sonic',             series: 'sonic' },
  { name: 'デデデ',            slug: 'king_dedede',       series: 'kirby' },
  { name: 'ピクミン&オリマー', slug: 'olimar',            series: 'pikmin' },
  { name: 'ルカリオ',          slug: 'lucario',           series: 'pokemon' },
  { name: 'ロボット',          slug: 'rob',               series: 'rob' },
  { name: 'トゥーンリンク',    slug: 'toon_link',         series: 'zelda' },
  { name: 'ウルフ',            slug: 'wolf',              series: 'starfox' },
  { name: 'むらびと',          slug: 'villager',          series: 'animalcrossing' },
  { name: 'ロックマン',        slug: 'mega_man',          series: 'megaman' },
  { name: 'Wii Fit トレーナー', slug: 'wii_fit_trainer',  series: 'wiifit' },
  { name: 'ロゼッタ&チコ',     slug: 'rosalina',          series: 'mario' },
  { name: 'リトル・マック',    slug: 'little_mac',        series: 'punchout' },
  { name: 'ゲッコウガ',        slug: 'greninja',          series: 'pokemon' },
  { name: 'Mii 格闘タイプ',    slug: 'mii_brawler',       series: 'mii' },
  { name: 'Mii 剣術タイプ',    slug: 'mii_swordfighter',  series: 'mii' },
  { name: 'Mii 射撃タイプ',    slug: 'mii_gunner',        series: 'mii' },
  { name: 'パルテナ',          slug: 'palutena',          series: 'kidicarus' },
  { name: 'パックマン',        slug: 'pac_man',           series: 'pacman' },
  { name: 'ルフレ',            slug: 'robin',             series: 'fireemblem' },
  { name: 'シュルク',          slug: 'shulk',             series: 'xenoblade' },
  { name: 'クッパJr.',         slug: 'bowser_jr',         series: 'mario' },
  { name: 'ダックハント',      slug: 'duck_hunt',         series: 'duckhunt' },
  { name: 'リュウ',            slug: 'ryu',               series: 'streetfighter' },
  { name: 'ケン',              slug: 'ken',               series: 'streetfighter' },
  { name: 'クラウド',          slug: 'cloud',             series: 'finalfantasy' },
  { name: 'カムイ',            slug: 'corrin',            series: 'fireemblem' },
  { name: 'ベヨネッタ',        slug: 'bayonetta',         series: 'bayonetta' },
  { name: 'インクリング',      slug: 'inkling',           series: 'splatoon' },
  { name: 'リドリー',          slug: 'ridley',            series: 'metroid' },
  { name: 'シモン',            slug: 'simon',             series: 'castlevania' },
  { name: 'リヒター',          slug: 'richter',           series: 'castlevania' },
  { name: 'キングクルール',    slug: 'king_k_rool',       series: 'dk' },
  { name: 'しずえ',            slug: 'isabelle',          series: 'animalcrossing' },
  { name: 'ガオガエン',        slug: 'incineroar',        series: 'pokemon' },
  { name: 'パックンフラワー',  slug: 'piranha_plant',     series: 'mario' },
  { name: 'ジョーカー',        slug: 'joker',             series: 'persona' },
  { name: '勇者',              slug: 'hero',              series: 'dragonquest' },
  { name: 'バンジョー&カズーイ', slug: 'banjo_kazooie',   series: 'banjo' },
  { name: 'テリー',            slug: 'terry',             series: 'fatalfury' },
  { name: 'ベレト/ベレス',     slug: 'byleth',            series: 'fireemblem' },
  { name: 'ミェンミェン',      slug: 'min_min',           series: 'arms' },
  { name: 'スティーブ',        slug: 'steve',             series: 'minecraft' },
  { name: 'セフィロス',        slug: 'sephiroth',         series: 'finalfantasy' },
  { name: 'ホムラ/ヒカリ',     slug: 'pyra_mythra',       series: 'xenoblade' },
  { name: 'カズヤ',            slug: 'kazuya',            series: 'tekken' },
  { name: 'ソラ',              slug: 'sora',              series: 'kingdomhearts' }
];
